Repository angelicaameira/DateCounter, pull requests merged in 2022-11, with the labels that each got.

#9 Implementa a tela de listagem de eventos #4
  DateCounter.xcodeproj/project.pbxproj
  DateCounter/DateCounter.xcdatamodeld/DateCounter.xcdatamodel/contents
  DateCounter/DateCounterApp.swift
  DateCounter/Views/AddEventView.swift
  DateCounter/Views/ContentView.swift
  DateCounter/Views/DetailView.swift
  DateCounter/Views/EventListRow.swift
  DateCounterTests/DateCounterTests.swift
Labels: enhancement

#17 #12: Move o editar para tela de adicionar
  DateCounter.xcodeproj/project.pbxproj
  DateCounter/DateCounter.xcdatamodeld/DateCounter.xcdatamodel/contents
  DateCounter/Views/ContentView.swift
  DateCounter/Views/DetailView.swift
  DateCounter/Views/EventListRow.swift
  DateCounter/Views/ManageEventView.swift
Labels: enhancement

#19 Closes #16: Altera a "data" na tela de lista para "quantidade de horas até o evento"
  DateCounter/Views/EventListRow.swift
Labels: enhancement

#20 Fixes #8 where editing events would cause issues
  DateCounter/Views/ManageEventView.swift
Labels: bug

#53 #52: Corrige apontamentos de code review
  DateCounter.xcodeproj/project.pbxproj
  DateCounter/DateCounter.xcdatamodeld/DateCounter.xcdatamodel/contents
  DateCounter/Views/ContentView.swift
  DateCounter/Views/DetailView.swift
  DateCounter/Views/FilteredList.swift
  DateCounter/Views/ManageEventView.swift
  DateCounter/Views/Preferences.swift
  EventIntents/IntentHandler.swift
  Widgets/SingleEventWidgets.swift
  Widgets/WidgetsBundle.swift
Labels: technical debt

#59 Refactors code, improves widget design and workflows
  DateCounter.xcodeproj/xcshareddata/xcschemes/DateCounter.xcscheme
  DateCounter/Views/ContentView.swift
  DateCounter/Views/DetailView.swift
  DateCounterUITests/DateCounterUITests.swift
  EventIntents/IntentHandler.swift
  Widgets/SingleEventWidgets.swift
Labels: technical debt

#63 Adds privacy policy
  DateCounter.xcodeproj/project.pbxproj
  PRIVACY.md
Labels: documentation

#69 Redesenha tela de detalhes
  .gitignore
  DateCounter.xcodeproj/project.pbxproj
  DateCounter/Resources/LunarEclipses.swift
  DateCounter/Views/ContentView.swift
  DateCounter/Views/DefaultDetailView.swift
  DateCounter/Views/DetailView.swift
  DateCounter/Views/ManageEventView.swift
  DateCounterUITests/DateCounterUITests.swift
Labels: enhancement

#71 Redesenha tela de detalhes (#69)
  .gitignore
  DateCounter.xcodeproj/project.pbxproj
  DateCounter/Resources/LunarEclipses.swift
  DateCounter/Views/ContentView.swift
  DateCounter/Views/DefaultDetailView.swift
  DateCounter/Views/DetailView.swift
  DateCounter/Views/ManageEventView.swift
  DateCounterUITests/DateCounterUITests.swift
Labels: release

#73 Adiciona suporte a plataforma watchOS
  DateCounter Watch App/DateCounter Watch App.entitlements
  DateCounter Watch AppTests/DateCounter_Watch_AppTests.swift
  DateCounter Watch AppUITests/DateCounter_Watch_AppUITests.swift
  DateCounter Watch AppUITests/DateCounter_Watch_AppUITestsLaunchTests.swift
  DateCounter-Watch-App-Info.plist
  DateCounter.xcodeproj/project.pbxproj
  DateCounter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DateCounter.xcodeproj/xcshareddata/xcschemes/DateCounter Watch App.xcscheme
  DateCounter/DateCounterApp.swift
  DateCounter/Info.plist
  DateCounter/Views/ContentView.swift
  DateCounter/Views/DetailView.swift
  DateCounter/Views/ManageEventView.swift
  DateCounterUITests/DateCounterUITests.swift
Labels: enhancement
