Repository angelicaameira/DateCounter, pull requests merged in 2022-12, with the labels that each got.

#78 Implementa CloudKit (iCloud Sync)
  DateCounter Watch App/DateCounter Watch App.entitlements
  DateCounter-Watch-App-Info.plist
  DateCounter.xcodeproj/project.pbxproj
  DateCounter/DateCounter.entitlements
  DateCounter/Info.plist
  DateCounter/Resources/Persistence.swift
  DateCounter/Views/ContentView.swift
Labels: enhancement

#81 Releases version 1.1
  DateCounter/Resources/Persistence.swift
  DateCounter/Views/ContentView.swift
  DateCounter/Views/Onboarding.swift
Labels: release

#84 Fixes widgets not working properly
  DateCounter Watch App/DateCounter-Watch-App-Info.plist
  DateCounter.xcodeproj/project.pbxproj
  DateCounter.xcodeproj/xcshareddata/xcschemes/DateCounter Watch App.xcscheme
  DateCounter/Resources/DateCounterCommands.swift
  DateCounter/Resources/Persistence.swift
  DateCounter/Views/ContentView.swift
  DateCounter/Views/ManageEventView.swift
  DateCounter/Views/Onboarding.swift
  DateCounterUITests/DateCounterUITests.swift
  EventIntents/EventIntents.entitlements
  EventIntents/IntentHandler.swift
  Widgets/SingleEventWidgets.swift
  Widgets/WidgetsExtension.entitlements
Labels: bug

#85 Releases version 1.1
  DateCounter Watch App/DateCounter-Watch-App-Info.plist
  DateCounter.xcodeproj/project.pbxproj
  DateCounter.xcodeproj/xcshareddata/xcschemes/DateCounter Watch App.xcscheme
  DateCounter/Resources/DateCounterCommands.swift
  DateCounter/Resources/Persistence.swift
  DateCounter/Views/ContentView.swift
  DateCounter/Views/ManageEventView.swift
  DateCounter/Views/Onboarding.swift
  DateCounterUITests/DateCounterUITests.swift
  EventIntents/EventIntents.entitlements
  EventIntents/IntentHandler.swift
  Widgets/SingleEventWidgets.swift
  Widgets/WidgetsExtension.entitlements
Labels: release
